//string[] dayOneInput = File.ReadAllLines("./Day01Input.txt");
//var dayOnePuzzle = new Day01(dayOneInput);
//Console.WriteLine($"Day 01 Part 01 Solution - {dayOnePuzzle.SolvePartOne()}");
//Console.WriteLine($"Day 01 Part 02 Solution - {dayOnePuzzle.SolvePartTwo()}");
//string[] dayTwoInput = File.ReadAllLines("./Day02Input.txt");
//var dayTwoPuzzle = new Day02(dayTwoInput);
//Console.WriteLine($"Day 02 Part 01 Solution - {dayTwoPuzzle.SolvePartOne()}");
//Console.WriteLine($"Day 02 Part 02 Solution - {dayTwoPuzzle.SolvePartTwo()}");
//string[] dayThreeInput = File.ReadAllLines("./Day03Input.txt");
//var dayThreePuzzle = new Day03(dayThreeInput);
//Console.WriteLine($"Day 03 Part 01 Solution - {dayThreePuzzle.SolvePartOne()}");
//Console.WriteLine($"Day 03 Part 02 Solution - {dayThreePuzzle.SolvePartTwo()}");
//string daySixInput = File.ReadAllText("./Day06Input.txt");
//var daySixPuzzle = new Day06();
//Console.WriteLine($"Day 06 Part 01 Solution - {daySixPuzzle.SolvePartOne(daySixInput)}");
//Console.WriteLine($"Day 06 Part 02 Solution - {daySixPuzzle.SolvePartTwo(daySixInput)}");
string daySevenInput = File.ReadAllText("./Day07Input.txt");
var daySevenPuzzle = new Day07(daySevenInput);
Console.WriteLine($"Day 07 Part 01 Solution - {daySevenPuzzle.SolvePartOne()}");
Console.WriteLine($"Day 07 Part 02 Solution - {daySevenPuzzle.SolvePartTwo()}");